feat: Add support for float in generate_series
GlareDB/glaredb pull request #1298
Opened 2023-07-12 09:47 UTC by adhish20

Fixes #1158

2023-07-12 13:31 UTC, vrongmeal requested changes
So we have a lot of repetition here. It'll be harder to extend this for numerics and timestamps this way later on.

We could have a trait defining schema, primitive type and a function that generates the batch from the `Vec`.

```rust
trait GenerateSeriesType {
    type PrimType: ...; // can be i64, f64 etc.
    const ArrowType: DataType; // for schema

    /// Collect a series batch into an arrow array with a compatible type to `Self::ArrowType`.
    fn collect_array(batch: Vec<Self::PrimType>) -> Arc<dyn Array>;
}
```

And hence we can have `GenerateSeriesPartition<T: GenerateSeriesType>`. A similar thing is done in the `decimal` crate.

2023-07-13 09:30 UTC, adhish20 commented on crates/sqlbuiltins/src/functions.rs
> +                    return Err(BuiltinError::Static("Unsupported param types"));
Added appropriate error message

2023-07-13 10:17 UTC, vrongmeal approved these changes
This looks good to go 🚀

2023-07-13 13:05 UTC, scsmithr approved these changes
Ship it!

2023-07-13 13:05 UTC, scsmithr commented on testdata/sqllogictests/functions/generate_series.slt
> +3.7
Nice, I was expecting that a first pass might only have _just_ floats or _just_ ints for args. Cool that they can be mixed.

2023-07-13 13:08 UTC, merged